name: fi_ducia
description: "FIDUCIA GPS tracking and geofencing module."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_alarm_manager_plus: ^4.0.8
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  flutter_activity_recognition: ^4.0.0
  flutter_map_mbtiles: ^1.0.4
  vector_map_tiles: any
  vector_map_tiles_mbtiles: any
  sqlite3_flutter_libs: any
  sqlite3: any
  vector_tile_renderer: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/branding/
    - assets/maps/

flutter_launcher_icons:
  image_path: assets/branding/fiducia_logo.png
  android: true
  ios: false
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/branding/fiducia_logo.png
  web:
    generate: true
    image_path: assets/branding/fiducia_logo.png
    background_color: "#FFFFFF"
    theme_color: "#0C2248"
  windows:
    generate: false
  macos:
    generate: false
